title: Furix Server Status Page
languageCode: en
params:
  copyrightHolder: Furix Inc.
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit furixmy.com'
    href='https://www.furixmy.com/'>furixmy.com</a> provides open-source
    software for all kind of sectors.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit furixmy.com'
    href='https://www.furixmy.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/furixmy'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Furix Server
  logo: /images/lclearstatus.svg
  meta_description: >-
    This status page provides updated information about our Furix Server systems
    normal operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: 'Furix Website '
      link: 'https://www.furixmy.com/'
      name: Furix Website
    - description: FURIX x MALAYSIA Server Status
      link: ''
      name: 'Furix FiveM Server '
    - description: Furix MC Server Status
      name: 'Furix MC Server '
  timezoneString: ' UTC'
