title: Furix Server Status Page
languageCode: en
params:
  copyrightHolder: Furix Inc.
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit furixmy.com'
    href='https://www.furixmy.com/'>furixmy.com</a> .
  description_header: This Webiste To View Furix Server Status
  eventsPerPage: 10
  groups:
    - Furix Server
  logo: ''
  meta_description: >-
    This status page provides updated information about our Furix Server systems
    normal operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: 'Furix Website '
      link: 'https://www.furixmy.com/'
      name: Furix Website
    - description: Furix FiveM Server Status
      link: ''
      name: 'Furix FiveM Server '
    - description: Furix MC Server Status
      name: 'Furix MC Server '
  timezoneString: ' UTC'
